# Generated by Django 6.0.2 on 2026-02-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backend',
            fields=[
                ('userID', models.IntegerField()),
                ('gameID', models.IntegerField()),
                ('backendID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('userID', models.IntegerField()),
                ('gameID', models.IntegerField()),
                ('favoritesID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('followers', models.IntegerField()),
                ('start_date', models.IntegerField()),
            ],
        ),
    ]
