# Generated by Django 6.0.2 on 2026-04-14 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gametime', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together={('userID', 'gameID')},
        ),
    ]
