# Generated by Django 6.0.2 on 2026-04-15 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gametime', '0002_alter_reviews_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='backlog',
            unique_together={('userID', 'gameID')},
        ),
        migrations.AlterUniqueTogether(
            name='completed',
            unique_together={('userID', 'gameID')},
        ),
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together={('userID', 'gameID')},
        ),
    ]
