# Generated by Django 6.0.2 on 2026-04-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gametime', '0003_alter_backlog_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='COMPLETED',
        ),
    ]
